datasource:
  default: ${APP_ENV}
  dev:
    username: ""
    password: ""
    url: "jdbc:h2:./database"
  prod:
#    username: ${JDBC_DATABASE_USERNAME}
#    password: ${JDBC_DATABASE_PASSWORD}
#    url: ${JDBC_DATABASE_URL}
    username: ${{PGUSER}}
    password: ${{PGPASSWORD}}
    url: jdbc:postgresql://${{PGHOST}}:${{PGPORT}}/${{PGDATABASE}}
ebean:
  migration:
    run: true
#  ddl:
#    run: true
#    generate: true
#    seedSql: seed.sql